deploy k8s refactored
[#139825037]

diff --git a/bin/deploy_k8s b/bin/deploy_k8s
--- a/bin/deploy_k8s
+++ b/bin/deploy_k8s
@@ -4,22 +4,92 @@ set -o pipefail
 
 [ -z "$DEBUG" ] || set -x
 
+
+echo "====================================="
+echo "|     BOSH K8S Cluster Deployer     |"
+echo "====================================="
+echo ""
+
+if [ $# -ne 2 ] && [ $# -ne 3 ]; then
+  print_usage
+  exit  1
+fi
+
+
+print_usage() {
+  echo "Usage: `basename $0` [BOSH_ENV] [DEPLOYMENT_NAME] [RELEASE_SOURCE]"
+  echo ""
+  echo "BOSH_ENV is the path to your BOSH environment configuration folder"
+  echo ""
+  echo "DEPLOYMENT_NAME is the name of your kubo deployment"
+  echo ""
+  echo "RELEASE_SOURCE specifies where to find the required BOSH releases"
+  echo "  options:"
+  echo "     dev    - Build a dev release from the local machine."
+  echo "              Required binaries and repos should be in ../"
+  echo "     public - Use published releases from the internet"
+  echo "     local  - Use local releases"
+  echo "              Required binaries should be in ../"
+  echo ""
+}
+
 main() {
-  upload_releases
-  set_cloud_config
-  deploy_to_bosh "$(bin/generate_service_manifest ${BOSH_ENV} ${DEPLOYMENT_NAME})"
+  local bosh_env=$(cd "${1}"; pwd -P)
+  local deployment_name="${2}"
+  local release_source="${3}"
+  local bosh_iaas
+
+  if [ -e "${bosh_env}/iaas" ]; then
+    bosh_iaas=$(cat "${bosh_env}/iaas")
+  else
+   echo "${bosh_env} is not a valid BOSH environment."
+   echo "Please use 'generate_bosh_config' to create one."
+   print_usage
+   exit 1
+  fi
+
+  case ${release_source} in
+    "dev"|"public"|"local") ;;
+    "") release_source="public";;
+    *) print_usage; exit 1;;
+  esac
+
+
+  pushd $(dirname $0)/.. > /dev/null
+    . ./bin/lib/deploy_utils
+
+    export_bosh_environment ${bosh_env}
+
+    upload_releases ${release_source}
+    set_cloud_config
+    set_kubernetes_certificate_in_credhub "$(basename ${bosh_env})/${deployment_name}/tls-kubernetes"
+    deploy_to_bosh "$(bin/generate_service_manifest ${bosh_env} ${deployment_name})" ${deployment_name}
+  popd > /dev/null
+}
+
+set_kubernetes_certificate_in_credhub() {
+  local secret_path=$1
+  local credhub_user_password=$(get_setting "creds.yml" "/credhub_user_password")
+  local credhub_api_url=https://$(get_setting "director.yml" "/internal_ip"):8844
+  local tcp_router_ip=$(get_setting "director.yml" "/cf-tcp-router-name")
+
+  credhub login -u credhub-user -p ${credhub_user_password} -s ${credhub_api_url} --skip-tls-validation
+  credhub generate -n ${secret_path} -t certificate -c ${tcp_router_ip} -a ${tcp_router_ip} -O
 }
 
 upload_releases() {
-  case $RELEASE_SOURCE in
+  local release_source=$1
+
+  case ${release_source} in
     "dev")
       pushd ../ > /dev/null
-	create_and_upload_release 'kubo-release'
-	upload_release "https://s3.amazonaws.com/kubo-public/etcd-85%2Bdev.1.tgz"
+        create_and_upload_release 'kubo-release'
+        upload_release "https://s3.amazonaws.com/kubo-public/etcd-85%2Bdev.1.tgz"
       popd > /dev/null
       ;;
     "public")
-       echo "NYI: Releases not yet avaliable on a public endpoint"
+       upload_release "https://s3.amazonaws.com/kubo-public/etcd-85%2Bdev.1.tgz"
+       echo "NYI: Kubo release not yet available on a public endpoint"
        exit 1
       ;;
     "local")
@@ -29,13 +99,9 @@ upload_releases() {
       popd > /dev/null
       ;;
     *)
-      echo "unknown RELEASE_SOURCE"
+      echo "unknown RELEASE_SOURCE: '${release_source}'"
       exit 1
     esac
 }
 
-pushd "$(dirname "$0")/../" > /dev/null
-  . ./bin/lib/deploy_utils
-  parse_deployment_args $@
-  main
-popd > /dev/null
+main $@
diff --git a/bin/lib/deploy_utils b/bin/lib/deploy_utils
--- a/bin/lib/deploy_utils
+++ b/bin/lib/deploy_utils
@@ -1,7 +1,20 @@
+#@IgnoreInspection BashAddShebang
 # vim: set ft=sh
 
+export_bosh_environment() {
+  export BOSH_ENV=$1
+  export BOSH_NAME=$(basename ${BOSH_ENV})
+}
+
 get_bosh_secret() {
-  bosh-cli int ${BOSH_ENV}/creds.yml --path=/bosh_admin_client_secret | xargs echo -n
+  get_setting "creds.yml" "/bosh_admin_client_secret"
+}
+
+get_setting() {
+  local file_name=$1
+  local value_path=$2
+
+  bosh-cli int ${BOSH_ENV}/${file_name} --path=${value_path} | xargs echo -n
 }
 
 set_cloud_config() {
@@ -10,31 +23,28 @@ set_cloud_config() {
 
 deploy_to_bosh() {
   local bosh_manifest=$1
+  local deployment_name=$2
 
-  if [ $# -ne 1 ]; then
-    echo "Bosh manifest is required in $0:deploy_to_bosh()"
+  if [ $# -ne 2 ]; then
+    echo "Bosh manifest and deployment name are required in $0:deploy_to_bosh()"
     exit 1
   fi
 
-  printf "${bosh_manifest}" | BOSH_CLIENT=bosh_admin BOSH_CLIENT_SECRET=$(get_bosh_secret) bosh-cli -e "$BOSH_NAME" -d ${DEPLOYMENT_NAME} -n deploy --no-redact -
+  printf "${bosh_manifest}" | BOSH_CLIENT=bosh_admin BOSH_CLIENT_SECRET=$(get_bosh_secret) bosh-cli -e "$BOSH_NAME" -d ${deployment_name} -n deploy --no-redact -
 }
 
 create_and_upload_release() {
-  local release_directory=$1
-  local release_name="${release_directory%-release}"
+  local release_dirname=$1
+  local release_name="${release_dirname%-release}"
 
-  if release_dir_exists "$release_directory"; then
-    pushd "$release_directory"
-
-      BOSH_CLIENT=bosh_admin BOSH_CLIENT_SECRET=$(get_bosh_secret) bosh-cli -e "$BOSH_NAME" create-release --force --name "${release_name}"
+  if [ -d "$release_dirname" ]; then
+    pushd "$release_dirname"
+      BOSH_CLIENT=bosh_admin BOSH_CLIENT_SECRET=$(get_bosh_secret) bosh-cli -e "${BOSH_NAME}" create-release --force --name "${release_name}"
       upload_release "--name=${release_name}" 
     popd
   else
-    echo "${release_directory} repo not found - skipping release create and upload"
-    if ! release_exists "${release_name}" ".*"; then
-      echo "${release_name} release not found on your BOSH director - unable to continue"
-      exit 1
-    fi
+    echo "${release_dirname} repo not found - unable to create the ${release_name} release"
+    exit 1
   fi
 }
 
@@ -44,101 +54,45 @@ upload_release() {
   BOSH_CLIENT=bosh_admin BOSH_CLIENT_SECRET=$(get_bosh_secret)  bosh-cli -e "$BOSH_NAME" upload-release "$release_name"
 }
 
-release_dir_exists() {
-  local release_directory="$1"
-
-  [ -d "$release_directory" ]
-}
-
 generate_manifest() {
   if [ $# -ne 3 ]; then
-    echo "Required arguments are bosh_target, deployment_name and deployment_type in $0:generate_manifest()"
+    echo "Required arguments are bosh_target and deployment_name in $0:generate_manifest()"
     exit 1
   fi
 
-  if [[ ! $3 =~ ^(odb|service)$ ]]; then
-    echo "Supported deployment types are 'odb' and 'service' in $0:generate_manifest()"
-    exit 1
-  fi
-
-  local bosh_target=$1
+  local bosh_environment=$1
   local deployment_name=$2
-  local deployment_type=$3
 
   pushd "$(dirname "${BASH_SOURCE[0]}")/../../" > /dev/null
-    manifest="$(cat "manifests/${deployment_type}.yml")"
+    manifest="$(cat "manifests/service.yml")"
 
-    if [ -e "${bosh_target}/${deployment_type}-${deployment_name}.yml" ]; then
-      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --ops-file="${bosh_target}/${deployment_type}-${deployment_name}.yml")
+    if [ -e "${bosh_environment}/service-${deployment_name}.yml" ]; then
+      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --ops-file="${bosh_environment}/service-${deployment_name}.yml")
     fi
 
-    if [ -e "${bosh_target}/${deployment_type}-${deployment_name}-vars.yml" ]; then
-      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --vars-file="${bosh_target}/${deployment_type}-${deployment_name}-vars.yml")
+    if [ -e "${bosh_environment}/service-${deployment_name}-vars.yml" ]; then
+      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --vars-file="${bosh_environment}/service-${deployment_name}-vars.yml")
     fi
 
     manifest=$(printf "%s" "${manifest}" | bosh-cli int - \
-        --vars-file="${bosh_target}/director.yml" \
+        --vars-file="${bosh_environment}/director.yml" \
         --var=deployment_name="${deployment_name}")
 
-    if [ -e "${bosh_target}/creds.yml" ]; then
-      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --vars-file="${bosh_target}/creds.yml")
+    if [ -e "${bosh_environment}/creds.yml" ]; then
+      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --vars-file="${bosh_environment}/creds.yml")
     fi
 
-    if [ -e "${bosh_target}/${bosh_target}-secrets.yml" ]; then
+    if [ -e "${bosh_environment}/director-secrets.yml" ]; then
       # local deployment, fill in credentials if a secrets file exists.
       # otherwise they will be filled in by CredHub
-      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --vars-file="${bosh_target}/${bosh_target}-secrets.yml")
+      manifest=$(printf "%s" "${manifest}" | bosh-cli int - --vars-file="${bosh_environment}/director-secrets.yml")
     fi
 
     manifest=$(printf "%s" "${manifest}" | bosh-cli int - \
-        --vars-store="${bosh_target}/${deployment_type}-${deployment_name}-creds.yml")
+        --vars-store="${bosh_environment}/service-${deployment_name}-creds.yml")
 
     manifest=$(printf "%s" "${manifest}" | bosh-cli int - --ops-file=manifests/ops-files/remove-variables.yml)
 
     printf "%s" "${manifest}"
   popd > /dev/null
-}
-
-display_deployment_usage() {
-  echo "Usage: `basename $0` [BOSH_ENV] [DEPLOYMENT_NAME] [RELEASE_SOURCE]"
-  echo ""
-  echo "BOSH_ENV is the path to your BOSH environment configuration folder"
-  echo ""
-  echo "DEPLOYMENT_NAME is the name of your deployment and service broker"
-  echo ""
-  echo "RELEASE_SOURCE specifies where to find the required BOSH releases"
-  echo "  options:"
-  echo "     dev    - Build a dev release from the local machine."
-  echo "              Required binaries and repos should be in ../"
-  echo "     public - Use published releases from the internet" 
-  echo "     local  - Use local releases"
-  echo "              Required binaries should be in ../"
-  echo ""
-}
-
-parse_deployment_args() {
-  if [ $# -ne 2 ] && [ $# -ne 3 ]; then
-    echo $#
-    display_deployment_usage
-    exit  1
-  fi
-
-  BOSH_ENV="$(realpath ${1})"
-  DEPLOYMENT_NAME="${2}"
-  RELEASE_SOURCE="${3}"
-  BOSH_NAME="$(basename ${BOSH_ENV})"
-
-  case $RELEASE_SOURCE in
-    "dev"|"public"|"local") ;;
-    "") RELEASE_SOURCE="public";;
-    *) display_deployment_usage; exit 1;;
-  esac
-
-  if [ -e "${BOSH_ENV}/iaas" ]; then
-    BOSH_IAAS=$(cat "$BOSH_ENV"/iaas)
-  else
-   echo "BOSH_ENV not found"
-   display_deployment_usage
-   exit 1
-  fi
 }
