Avoid setting cloud config to invalid value
* Print cloud config error on stderr
* Start piping cloud config to bosh-cli only on success

Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

diff --git a/bin/generate_cloud_config b/bin/generate_cloud_config
--- a/bin/generate_cloud_config
+++ b/bin/generate_cloud_config
@@ -45,13 +45,12 @@ main() {
     elif [ "openstack" == "${bosh_iaas}" ]; then
         cloud_config=$(bosh-cli int "$(repo_directory)/configurations/${bosh_iaas}/cloud-config.yml" --vars-file ${bosh_env}/director.yml)
     else
-      echo "ERROR: Proxy routing mode not supported on [${bosh_iaas}]"
+      echo "ERROR: Proxy routing mode not supported on [${bosh_iaas}]" >&2
       exit 1
     fi
 
   else
     cloud_config=$(bosh-cli int "$(repo_directory)/configurations/${bosh_iaas}/cloud-config.yml" --vars-file ${bosh_env}/director.yml)
-
   fi
 
   echo -n "${cloud_config}"
