Addons can be provided to k8s manifest.
[#152647926]

Signed-off-by: Iain Sproat <isproat@pivotal.io>

diff --git a/bin/lib/deploy_utils b/bin/lib/deploy_utils
--- a/bin/lib/deploy_utils
+++ b/bin/lib/deploy_utils
@@ -136,5 +136,28 @@ generate_manifest() {
     manifest=$(bosh-cli int <(echo "${manifest}") --vars-file="${bosh_environment}/director-secrets.yml")
   fi
 
+
+  if bosh-cli int "${bosh_environment}/director.yml" --path='/addons_spec_path' &> /dev/null; then
+    addon_path=$(bosh-cli int "${bosh_environment}/director.yml" --path='/addons_spec_path')
+    addon_path="${bosh_environment}/${addon_path}"
+    if [[ ! -f "${addon_path}" ]]; then
+      echo "No file exists at the path specified in addons_spec_path parameter of director.yml"
+      exit 1
+    fi
+
+    if ! bosh-cli int "${addon_path}" &> /dev/null; then
+      echo "Invalid yaml at the path specified for the addons_spec_path parameter of director.yml"
+      exit 1
+    fi
+
+    cat ${manifest_dir}/ops-files/addons-spec.yml > ./temp-opsfile.yml
+    sed  's/^/     /' ${addon_path} >> ./temp-opsfile.yml # indent yaml
+
+    manifest=$(bosh-cli int <(echo "${manifest}") --ops-file=./temp-opsfile.yml)
+
+    rm ./temp-opsfile.yml
+
+  fi
+
   printf "%s" "${manifest}"
 }
